version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-crossfit
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootdb
      MONGO_INITDB_ROOT_PASSWORD: passdb
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/var/lib/mongodb/data

  node:
    build: .
    container_name: node-crossfit
    restart: always
    ports:
      - 4044:4044
    depends_on:
      - mongo
