version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootdb
      MONGO_INITDB_ROOT_PASSWORD: passdb
    ports:
      - 27017:27017
      
  node:
    build: .
    restart: always
    ports:
      - 4044:4044
